### ISSUE TITLE
increase decimal places

### ISSUE THREAD

**Issue by rdg2001** [aviddot/Pancakeswap-and-uniswap-trading-bot#21]
your version of tradingbot.exe cannot see currency prices with more decimal places?

Example tokem:
0x4C8307cF2cfAFCAb5653c25e1870b905488bD830
price 0.000000000231499

but in the app he only sees up to 0.00000000

**Comment by aviddot** [comment]
Made it 13 decimals. 
![image](https://user-images.githubusercontent.com/72505611/121777306-a0004200-cb91-11eb-8a6d-0c247eaa3108.png)

Will upload new version in 20 minutes

**Comment by aviddot** [comment]
https://github.com/aviddot/Pancakeswap-and-uniswap-trading-bot/releases/tag/v2.0.2
