### ISSUE TITLE
Buy never completes, just loops endlessly

### ISSUE THREAD

**Issue by joshcomley** [aviddot/Pancakeswap-and-uniswap-trading-bot#22]
Hi there,

Thanks for the project - however I cannot get mine to complete a purchase.

I am using `BNB` with a Binance Smart Chain address as my main token, NAFT (0xD7730681B1DC8f6F969166B29D8A5EA8568616a3) as my purchase, 1% as my slippage.

In debug mode I get these messages on each loop through attempting to buy:

    Non-hexadecimal digit found on line: 1527
    'NoneType' object is not subscriptable on line: 1715

Any thoughts?

**Comment by aviddot** [comment]
I think you inserted your seed phase instead of your private key in the bot. 

https://metamask.zendesk.com/hc/en-us/articles/360015289632-How-to-Export-an-Account-Private-Key

Or either the token address your inputed address is wrong

**Comment by joshcomley** [comment]
Hi @aviddot, thank you, you were absolutely right: once I put in the private key it worked.
