### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by brendanhernou** [aviddot/Pancakeswap-and-uniswap-trading-bot#23]
Hey,

Please refund me my 300 BUSD to:  0xe7B2b78455261E118D4285dfC2DfD49beC093fe8

You deleted the previous Github issue, but I have been waiting for weeks on a reply now. 

Thanks!

**Comment by aviddot** [comment]
I told you to contact via telegram and you did not after asking for 3 times, I left the issue there for 4 days and you were the one not answering

**Comment by aviddot** [comment]
Please talk to @aviddotsupport , so I can also see that you are who you say you are...
