### ISSUE TITLE
Wrong price on some coins

### ISSUE THREAD

**Issue by BatavianX** [aviddot/Pancakeswap-and-uniswap-trading-bot#24]
Tried with different address, all I got even more different prices, my guess you got ghost 'variable' somewhere.

![Screenshot_14](https://user-images.githubusercontent.com/85840771/121816451-e21aa800-cca5-11eb-9ce1-dcde15e9474f.jpg)
![Screenshot_13](https://user-images.githubusercontent.com/85840771/121816455-e777f280-cca5-11eb-9f3e-81aa50f3c181.jpg)

**Comment by BatavianX** [comment]
At first picture I got 0.000000005x price diff.
With second profile at second picture I got 0.000000007x price diff.

**Comment by aviddot** [comment]
This is not the wrong price, the price that you see takes already in consideration the price impact of the amount you want to buy or sell

**Comment by BatavianX** [comment]
I wasn't set anything see 1st screenshot, only for price monitoring.

**Comment by aviddot** [comment]
Indeed the amount you are trading with is too low to have those big impacts. I think the token has an extra fee when trading, and the bot also takes into consideration that in the price, could that be the case?

**Comment by BatavianX** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/85840771/121825526-2bd2b500-ccdd-11eb-9017-dffa8b4f8d5f.jpg)

Here another screenshot, this time with Cake Token, with price difference of $0.03xx huge gap with the previous two, I meant if the bot is intended to work like that, different from other price monitoring chart, then so be it, thanks anyway.

**Comment by BatavianX** [comment]
![Screenshot_17](https://user-images.githubusercontent.com/85840771/121826258-08aa0480-cce1-11eb-9418-35855e0bcabf.jpg)

Last SS, even weirder, now it's cheaper by $0.000000002x.

**Comment by aviddot** [comment]
With Cake, thats just normal as poocoin takes different bnb prices than my bot. My bot bnb prices are based on the market price on binance.

For Golden Inu, I think the prices are right, but both the bot and poocoin get updated differently, and make it look like its very different. I just went on poocoin to check the price of golder inu and it changed very often, just like what your log is showing.

**Comment by aviddot** [comment]
> ![Screenshot_15](https://user-images.githubusercontent.com/85840771/121825526-2bd2b500-ccdd-11eb-9017-dffa8b4f8d5f.jpg)
> 
> Here another screenshot, this time with Cake Token, with price difference of $0.03xx huge gap with the previous two, I meant if the bot is intended to work like that, different from other price monitoring chart, then so be it, thanks anyway.


0.03/16.80=~0.2% == The fee you pay on pancakeswap per trade
