### ISSUE TITLE
Bot is stuck at "(re)Preparing bot..."

### ISSUE THREAD

**Issue by sidmish** [aviddot/Pancakeswap-and-uniswap-trading-bot#25]
I am purchasing token with BNB.
Bot  has been stucked at 

"Starting bot
Approving Pancake...
(re)Preparing bot..."

What could be the issue?

**Comment by aviddot** [comment]
Can you provide more information please, such as a screenshot of your settings?

And please make sure you inserted your pk and address the correct way in the configfile.py
