### ISSUE TITLE
web3 module missing

### ISSUE THREAD

**Issue by Jaiswaljaswant** [aviddot/Pancakeswap-and-uniswap-trading-bot#26]
when execute the  pancakeswap_bot.py,  following error occurs

![Capture](https://user-images.githubusercontent.com/85819229/122676232-d32e7b00-d1fa-11eb-9a9b-2c84c62bf97a.JPG)

----> 8 from web3 import Web3
      9 from web3.eth import Contract
     10 from web3.contract import ContractFunction

ModuleNotFoundError: No module named 'web3'

**Comment by arenmarsden** [comment]
Make sure you have web3 installed via pip
