### ISSUE TITLE
Question/Doubt

### ISSUE THREAD

**Issue by Diogovski** [aviddot/Pancakeswap-and-uniswap-trading-bot#27]
Is this free?

**Comment by aviddot** [comment]
Yes, the tradingbot is free to use, you can get what you need from this repository

**Comment by Diogovski** [comment]
I tried using it but he never buys, only checks for the price. He was avle
to approve but nothing else.

A terça, 22/06/2021, 09:58, aviddot ***@***.***> escreveu:
