### ISSUE TITLE
How to set the slippage of different tokens?

### ISSUE THREAD

**Issue by CnKore-zzb** [aviddot/Pancakeswap-and-uniswap-trading-bot#33]
I have some questions as follows
1.How to set the slippage of different tokens?
2.If there are three tokens, how are the purchased quantities distributed?

**Comment by aviddot** [comment]
1. Same slippage is used with all the tokens you set the bot to tade with.
2. The bot trades with the full balance of the main coin/token of your wallet, and trades it with whatever tokens hit your set limits first. You can also set the bot to let the tokens trade with each other. For the latter, please refer to the information about the 'tokentokennumerator' in the homepage of the repository
