### ISSUE TITLE
AVAST and AVG flag the exe as virus/trojan MDEClass W64

### ISSUE THREAD

**Issue by ericlatina** [aviddot/Pancakeswap-and-uniswap-trading-bot#6]
I'm not convinced that it is a false positive. Can you provide some insight as to why this happens?

**Comment by Terra-Incognita-888** [comment]
Are you having any issues with it ? I am also worried it might be a malware. But I have no proof

**Comment by aviddot** [comment]
I can only say it is not, but this is coming from the one who wrote the bot. It is very common for antivirus to flag safe exe's, and it could also be someone reported the bot on virustotal.com as a virus, and the scanners like avast taking this threat serious too fast.

It would be nice if someone other than me could reverse engineer the exe's and tell it's alright.

**Comment by ericlatina** [comment]
Two machines with different AV, warnings on both. That's all I have to show anyone. I know that this happens sometimes with files that are completely benign, I'm just not sure I wish to connect a wallet to it in this current state.
You are correct, I don't often download compiled exe's from github. Hope you sort this out as it looks like a wonderful package.

**Comment by samkitpalecha** [comment]
I've been using it with McAfee and no issues tbh.

**Comment by gasmetervalve** [comment]
Can I run this just using python? I don't need a GUI ...

**Comment by aviddot** [comment]
> Can I run this just using python? I don't need a GUI ...

Please check the source file map and this issue here: https://github.com/aviddot/Pancakeswap-v2-trading-bot/issues/13

**Comment by GGLabCenter** [comment]
Hi, so the application is closed-source?

**Comment by GGLabCenter** [comment]
Hi, will the source be updated to 2.0? So one will be able eventually to build the exe himself, or run from a python deamon directly (win).

**Comment by aviddot** [comment]
> Hi, will the source be updated to 2.0? So one will be able eventually to build the exe himself, or run from a python deamon directly (win).

Yes it will in some days, im working now on the cross platform compatibility (Mac OS and Linux) and will update the bot then.
